name: "build"

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  SKIP_TESTS: 1

jobs:
  build-macos-x64:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@v6
      with:
        node-version: '22'
    - uses: actions/setup-go@v6
      with:
        go-version: '^1.22.1'

    - name: Install dependencies
      run: |
        npm ci

    - name: Type check
      run: |
        npm run ts-check

    - name: Build and package (x64)
      run: |
        node release/package-all.js --os darwin --arch amd64

    - name: Create tarball to preserve symlinks
      run: |
        cd artifacts/darwin-amd64
        tar -cf ../darwin-amd64.tar .

    - name: Upload artifact
      uses: actions/upload-artifact@v6
      with:
        name: ${{ github.ref_type == 'tag' && !endsWith(github.ref_name, '-canary') && 'itch' || 'kitch' }}-${{ github.event_name == 'pull_request' && 'pr' || github.ref_name || 'main' }}-darwin-amd64
        path: artifacts/darwin-amd64.tar
